config/routes.rb
Rails.application.routes.draw do
  root 'home_pages#home'
  get     '/help',    to: 'home_pages#help'
  get     '/about',   to: 'home_pages#about'
  get     '/contact', to: 'home_pages#contact'
  get     '/signup',  to: 'users#new'
  post    'signup',   to: 'users#create'
  get     '/login',   to: 'sessions#new' 
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :micropost, counter_cache: :likes_count
    belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_micropost
    
    def create
        @like  = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
        @likes = Like.where(micropost_id: params[:micropost_id])
        @micropost.reload
    end
    
    def destroy
        like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
        like.destroy
        @likes = Like.where(micropost_id: params[:micropost_id])
        @micropost.reload

    end
    
    private
    def set_micropost
    @micropost = Micropost.find(params[:micropost_id])
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if logged_in? %>
  <% if micropost.like_user(current_user.id) %>
    <%= button_to micropost_like_path(@likes, micropost_id: micropost.id), method: :delete, id: "like-button#{micropost.id}", remote: true do %> 
      <%= image_tag("icon_red_heart.png") %>
      <span>
        <%= micropost.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to micropost_likes_path(micropost_id: micropost.id),id: "like-button#{micropost.id}", remote: true do %>  
      <%= image_tag("icon_heart.png") %>
      <span>
        <%= micropost.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <!--<%= image_tag("icon_heart.png") %>-->
  <!--  <span>-->
  <!--    <%= micropost.likes_count %>-->
  <!--  </span>-->
<% end %>

app/views/likes/create.js.erb
$("#like-button<%= @micropost.id %>").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-button<%= @micropost.id %>").html("<%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes }) %>");